package EnumRelated;

public enum enumMsgBox 
{
    LOGINSUCCESSFULL,INVALIDLOGIN,ENTERREQUIREDFIELDS,REGISTERSUCCESSFULL,DELETED,INCORRECTID,
    DATASAVEDSUCCESSFULLY,INCORRECTMEDIAID,ISSUED,RECIEVED,CANTWRITETODATA,NOCUSTOMERAVAILABLE,ERROR,PLEASEENTERID;
}
